---
- hosts: localhost
  gather_facts: no

  module_defaults:
    group/aws:
      region: "us-east-2"

  tasks:
    # create public subnets
    - name: create public subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2a"
        cidr: 10.64.1.0/24
        tags:
          Name: lcortez-public-1
        state: present
      register: pubis1

    - name: create public subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2b"
        cidr: 10.64.2.0/24
        tags:
          Name: lcortez-public-2
        state: present
      register: pubis2

    - name: create public subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        az: "us-east-2c"
        cidr: 10.64.3.0/24
        tags:
          Name: lcortez-public-3
        state: present
      register: pubis3